services:
  - type: web
    name: todo-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString

databases:
  - name: todo-db
    ipAllowList: []